- src/dag.ts
- test/dag.ts
- tsconfig.json
fix: detect circular deps in Dag and enable strictPropertyInitialization in tsconfig.json
> fix: detect circular deps in Dag

- README.md
- src/cli.ts
- src/commands/serve.ts
- src/duckconfig.ts
Fixes #69
Info: https://www.fastify.io/docs/latest/HTTP2/
> feat(serve): support https and http2

- .gitignore
Are you adding `node_modules/` into `.gitignore` as a global config?
I think it should be added `.gitignore` in the repository for other contributors 😄
> chore: add node_modules into gitignore

- .eslintignore
- package.json
- test/bin-test/bin.js
To prevent such bugs again: https://github.com/teppeis/duck/pull/84
> test: add test for bin/duck.js

- README.md
- src/batch.ts
- src/cli.ts
- src/commands/buildJs.ts
- src/compiler-core.ts
- src/duckconfig.ts
BREAKING CHANGE: Now --batch option is not boolean but choice of "aws"
or "local". Also --compilerPlatform option is removed.
> feat: change --batch option to specify aws or local

- src/cli.ts
BREAKING CHANGE: --skipInitialSoy is renamed to --skipInitialBuild
> feat: generate deps.js in build and serve commands

- src/commands/serve.ts
ref. https://github.com/fastify/fastify/commit/073f7476ccecb9eed28ccaae26c5351a0406d148
> fix: improve log output in serve command

- .circleci/config.yml
- .codecov.yml
Document: [Pull Request Comments](https://docs.codecov.io/docs/pull-request-comments)
```yaml
comment:
layout: "diff, files"
```
Removed reach graph
> ci: add .codecove.yml to customize pr comment

- README.md
- package-lock.json
- package.json
- src/cli.ts
- src/commands/buildJs.ts
- src/compiler-core.ts
- src/duckconfig.ts
- src/report.ts
- src/reporters/text-reporter.ts
- src/reporters/xunit-reporter.ts
- test/text-reporter.ts
- test/xunit-reporter.ts
> feat: add XUnit reporter

- .codecov.yml
- https://docs.codecov.io/docs/coverage-configuration
- https://docs.codecov.io/docs/commit-status
> build(codecov): disable commit status

- src/cli.ts
new typing has type parameters: https://github.com/teppeis/duck/pull/168
> fix: improve typings of listr

- src/dependency-parser-wrapper.ts
for https://github.com/teppeis/duck/pull/210
> fix: update options for workerpool v5

- src/cli.ts
This PR fixes the below:
> 2. when we use duck build:js instead of duck build, the warnings isn't printed. Is it intentional?
> https://github.com/teppeis/duck/pull/296#issuecomment-555804880
> fix: enable output warnings in build:js

- src/cli.ts
- src/commands/buildJs.ts
- src/commands/serve.ts
- src/compiler-core.ts
- src/compiler.ts
- src/report.ts
- src/reporters/text-reporter.ts
- src/reporters/xunit-reporter.ts
- test/text-reporter.ts
> feat: output warnings

- .mocharc.json
- examples/build-deps/.eslintrc.json
- package.json
- src/commands/buildDeps.ts
- src/commands/buildJs.ts
- src/commands/serve.ts
- src/duckconfig.ts
- src/entryconfig.ts
- src/gendeps.ts
- src/reporters/base-reporter.ts
- src/watch.ts
- test/bin-test/bin.js
- test/gendeps.ts
- test/json-reporter.ts
- test/xunit-reporter.ts
- types/google-closure-deps.d.ts
> fix: update minimum Node version to 10.17

- README.md
- src/cli.ts
- src/commands/buildSoy.ts
- src/duckconfig.ts
- src/soy.ts
- src/watch.ts
- test/soy.ts
This PR adds the `soyClasspaths` option to specify classpaths for Closure Templates such as JAR file of plugin.
> feat: add soyClasspaths option

- src/assert.ts
> chore: Use unknown instead of any in assert functions

- .github/workflows/lint.yml
- package.json
Fixes #592
Please merge this after #593 is merged.
> chore: run lint on GitHub Actions

- .github/workflows/test.yml
- package-lock.json
- package.json
Fixes #591
Should we do anything else?
> Drop node 10

- package-lock.json
- package.json
> Update workerpool to ^6.1.4

- package-lock.json
- package.json
> chore: remove @types/glob

- types/merge-options.d.ts
..because merge-options has declaration file now. ( https://github.com/schnittstabil/merge-options/blob/2b96ee3e6e9b276b1410d239c7e20e3326fdd6cd/index.d.ts )
> chore: remove merge-options.d.ts

- .github/workflows/lint.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
> chore!: support Node v16+

- examples/.eslintrc.json
- examples/build-and-serve/js/chunks.js
introduced by https://github.com/cybozu/duck/commit/b1efa12773f20220bd8cf69282984b6ad9048c2d
> chore(examples): disable eslint dot-notaion for Closure ADVANCED mode

- package-lock.json
- package.json
- src/commands/serve.ts
See [Migration-Guide-V4](https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/)
> fix(deps): update fastify to v4

- package-lock.json
- package.json
fix https://github.com/cybozu/duck/issues/720
> chore(deps): update typescript to v4.7

- src/cli.ts
- src/commands/cleanSoy.ts
- src/duckconfig.ts
- src/pathutils.ts
- src/soy.ts
- src/watch.ts
- test/soy.ts
> feat(soy): support soyOptions.outputDirectory

- package-lock.json
- package.json
- src/batch.ts
- src/commands/buildJs.ts
- src/compiler-batch-utils.ts
- src/compiler-batch-wrapper.ts
- src/compiler-core.ts
- test/compiler-batch-utils.test.ts
fix #635, fix #678, fix #740 
faastjs v4 introduced 256kb limit of return value and async generator functions as faast modules.
https://github.com/faastjs/faast.js/releases/tag/v4.0.0
This PR uses the async generator feature for large code base over 256kb.
> fix(batch): update faastjs to v6 and use async generator for faastjs module function

- src/commands/buildJs.ts
From faastjs v3 to v6, the error format from faast module functions was changed.
> fix(batch): handle compile errors in batch mode
