bin/duck.js
Currently, `duck` is being broken by the following error.
> Error: Cannot find module '../lib/src/cli'
This seems to be introduced by https://github.com/teppeis/duck/commit/89c18dabd6f4768b972e9f46486a62ba857cd0d0
=> fix: update a require path from bin/duck

package-lock.json, package.json, src/commands/serve.ts
> [Announcing TypeScript 3.5 RC | TypeScript](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/)
Build performance improvement of tsc (v3.4 → v3.5 RC)
- clean build: 3.3s → 3.0s
- incremental build: 1.7s → 1.4s
Also fixed the typing of `faast()` for new tsc that detects type errors more accurately.
=> build(deps): update typescript to 3.5 RC

.eslintignore, src/commands/buildDeps.ts, src/commands/serve.ts, src/compiler.ts, src/duckconfig.ts, src/gendeps.ts, src/watch.ts, test/fixtures/writeCachedDepsOnDisk/deps.js, test/gendeps.ts
- improve watch log format
- watch ignores `config.depsJs` and `config.depsJsIgnoreDirs`
=> feat: update deps.js on disk in serve command

.circleci/config.yml, package-lock.json, package.json, renovate.json, src/commands/buildJs.ts, src/compiler-core.ts, src/compiler.ts, src/report.ts, test/compiler.ts
BREAKING CHANGE: google-closure-compiler was moved from deps to peerDeps
=> feat: widen supported version range of google-closure-compiler

src/compiler.ts, test/compiler.ts
=> fix: snake-case keys of experimental-compiler-options

src/compiler.ts
Currently, the following error occurs when I run `duck build` with a chunk entry config on AWS batch mode
```
Cannot read file /Users/koba04/project/path/to/js
```
The reason why the error happens is that JS files in compiler options are absolute path in my local machine.
This PR makes the path a relative path.
=> fix: chunk entries don't work on AWS batch mode

README.md
This is a typo, isn’t it?
https://faastjs.org/docs/api/faastjs.awsoptions
=> docs: fix a typo README (awsLambdaOptions)

package.json, src/gendeps.ts
`duck serve` doesn't work with dead symlink. That's why [recursive-readdir](https://github.com/jergason/recursive-readdir) occurs an error when 'inputsRoot' directory includes some dead symlinks.
There is a [PR](https://github.com/jergason/recursive-readdir/pull/60/files) to fix it. 
However, recursive-readdir is not active very much. The PR was created over a year ago.
So, I recommend to use [glob](https://github.com/isaacs/node-glob) instead of recursive-readdir.
=> fix: build doesn't work if inputsRoot dir includes dead symlink

src/gendeps.ts
#225 breaks our tests because `glob` doesn't follow symlinks by default, which is not the behavior with `recursive-readdir`.
This PR adds an option to be able to follow symlinks.
=> fix: follow symlinks in deps.js

README.md
=> docs: fix a link to example in readme

package.json
=> fix: don't install google-closure-deps@20191027.0.1

src/commands/buildJs.ts, src/reporters/text-reporter.ts
This fixes 1. of https://github.com/teppeis/duck/pull/296#issuecomment-555804880
Before
```
➜  npx duck build
✔ Compile Soy templates
✔ Generate deps.js
✔ Compile JS files
0 error(s), 0 warning(s), 98.4% typed
➜
```
After
```
➜  npx duck build
✔ Compile Soy templates
✔ Generate deps.js
✔ Compile JS files
➜
```
=> fix: format output without warnings

.circleci/config.yml, package.json, src/report.ts, src/reporters/text-reporter.ts, src/reporters/xunit-reporter.ts, test/text-reporter.ts, test/xunit-reporter.ts
BREAKING CHANGE: no longer support google-closure-compiler@<20180910.1.0
Fixes https://github.com/teppeis/duck/issues/282#issuecomment-558919454
Does this `key` become not optional?
https://github.com/teppeis/duck/blob/master/src/report.ts#L13
=> deps: update closure-compiler version in peerDeps

src/commands/buildJs.ts
duck fails to output json report when error occurs.
The reason is that it cannot parse message including 'logUrl' to JSON.
Error message is like the below. In this case, the line `: https://ap-northeast-1.console...` is logUrl.
```
Unexpected non-JSON error: /opt/nodejs/node_modules/google-closure-compiler-linux/compiler --rewrite_polyfills=true ...
[{"level":"error","description":"The result of a goog.define call must be assigned as an isolated statement.", ...},{"level":"info","description":"70 error(s), 0 warning(s)"}]
: https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#logEventViewer:group=%2Faws%2Flambda%2Ffaast-b0d763dd-d988-4d38-a357-485f28d8ef5e;stream=2020%2F01%2F30%2F%5B%24LATEST%5D12d386dbf1fe4ca9933e07671ca6956c;filter=%22575f34df-23ac-47a3-b0d …
```
=> fix: fail to output json with batch option 'aws'

package-lock.json
Currently, npm ci is failing because of "Cannot find module 'nan'", so I've reinstalled `faastjs` to fix this.
=> deps: fix missing nan as a dependency

src/cli.ts
This PR fixes the below error which is happened at the branch updating TS to 3.9([CI](https://app.circleci.com/pipelines/github/cybozu/duck/1993/workflows/9bbe8292-f170-4d86-9857-300b9a33a5d7/jobs/5044)):
```
src/cli.ts(201,9): error TS2783: 'depsJs' is specified more than once, so this usage will be overwritten.
```
=> fix(cli): fix TS2783 error

.github/workflows/test.yml
Currently, Renovate doesn't work as I expected. The reason is that we only run GItHub Actions for branches that has a PR, which causes a pending commit status and Renovate skips creating a PR due to the status.
I've changed to run GitHub Actions for branches that Renovate creates.
=> ci: run GitHub Actions for branch push by Renovate

src/commands/buildDeps.ts
If we run `duck build:deps` first, it will fail.
=> fix: make directories recursively to generate deps.js

.eslintrc.json, examples/build-and-serve/js/chunks.js, src/batch.ts, src/compiler.ts, src/entryconfig.ts
Preparation of #592
**before:**
```sh
$  npm run lint
> @cybozu/duck@0.32.8 lint
> eslint --ext js,ts src test types examples
/duck/examples/build-and-serve/js/chunks.js
15:3  warning  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
/duck/src/batch.ts
29:5  warning  Do not nest ternary expressions  no-nested-ternary
/duck/src/commands/buildJs.ts
83:9  warning  Async arrow function expected no return value  consistent-return
/duck/src/commands/serve.ts
197:18  warning  Expected to return a value at the end of async function 'replyChunksCompile'  consistent-return
/duck/src/compiler-core.ts
125:70  warning  Expected to return a value at the end of arrow function  consistent-return
/duck/src/compiler.ts
42:1  warning …
```
=> chore: remove lint warnings

src/commands/buildJs.ts
Currently, if `entryConfigDir` is not specified, the following error occurs. This doesn't tell us anything about what is going on.
```
$  npx duck build
↓ Compile Soy templates [skipped]
✔ Generate deps.js
✖ Compile JS files
→ Should be string: undefined
TypeError: Should be string: undefined
```
=> Show friendly message for missing entryConfigDir

.github/workflows/lint.yml, .github/workflows/test.yml
ref: https://github.com/actions/setup-node#caching-packages-dependencies
Now we can enable cache for npm dependencies with `actions/setup-node@v2`
=> chore: enable cache for npm on GitHub Actions

package-lock.json
Node v16+ bundles npm v8, which generates `lockfileVersion` v2.
=> chore: update lockfileVersion of package-lock.json to v2

.eslintrc.json, package-lock.json, package.json, src/commands/serve.ts, src/gendeps.ts
`@cybozu/eslint-config@17` warns `@typescript-eslint/no-non-null-assertion`.
Some reported lines were disabled because there was no apparent problem, others were not modified.
That will be fixed in another issue.
=> chore(deps): update to eslint@8 and @cybozu/eslint-config@17

src/gendeps.ts, test/gendeps.ts
See https://github.com/mrmlnc/fast-glob#how-to-exclude-directory-from-reading
> ⚠️ When you write `!**/second/**/*` it means that the directory will be read, but all the entries will not be included in the results.
Also this fixes example/build-deps including symlink loop.
=> perf(gendeps): optimize depsJsIgnoreDirs pattern for fast-glob

package-lock.json, package.json, src/commands/buildDeps.ts, src/commands/serve.ts, test/compiler-output.ts
Update to `~4.5.5` instead `^4.5.5`.
Cannot easily update to TS 4.6+.
See https://github.com/cybozu/duck/issues/720
=> chore(deps): update typescript to v4.5

package-lock.json, package.json, src/commands/buildSoy.ts, src/commands/serve.ts, src/compiler.ts, src/gendeps.ts, types/array.prototype.flat.d.ts
ES2019 is supported in Node now
=> fix: use native array .flat() instead shim library

src/commands/cleanSoy.ts, src/duckconfig.ts, src/soy.ts, src/watch.ts, test/soy.ts
Removed in https://github.com/google/closure-templates/commit/88c3d5b1e467d03bc6b3924e1069a9f43f48de79, closure-templates `2019-03-07` release.
=> fix(soy)!: remove soyOptions.inputPrefix for old closure-templates option

src/duckconfig.ts
No longer necessary because currently support `>=20180910.1.0`.
https://github.com/cybozu/duck/blob/bf3515cde06b041238f4d5321a557880072d2815/package.json#L63
=> fix(duckconfig): remove validation logic for unsupported old compiler

src/batch.ts
faast.js has added support for Node.js 18.x by adding the `webpackAwsSdk` option. If you set it to `true`, AWS SDK v2 will be bundled by webpack. However, duck will override this option because `/^aws-sdk/?/` is included in the externals of webpackOptions by default.This PR fixes that.
=> fix(batch): make the `webpackAwsSdk` option available in batchOptions

package-lock.json, package.json
close https://github.com/cybozu/duck/pull/864
The latest `tempy@3.1.0` has `temp-dir@3` in the deps.
https://github.com/sindresorhus/tempy/commit/5a4cb2b63db90cc353b5c649a0a59419432c8d00
`temp-dir@3` includes top-level await.
https://github.com/sindresorhus/temp-dir/blob/v3.0.0/index.js
But `webpack@4` in `faastjs@6` doesn't allow it and duck throws an error for batch compilation.
ref: https://github.com/cybozu/duck/actions/runs/5952268350/job/16143868194?pr=864
=> fix: pin tempy to 3.0.0 to prevent a webpack error

src/watch.ts
While `soySrcsRelativeFrom` option was added in #754 to change the working directory of compiler execution, the option was not respected on incremental compilation (watch command). I fixed the watch command to pick the `soySrcsRelativeFrom` value on incremental compilation, too.
=> fix(soy): respect soySrcsRelativeFrom option on incremental compilation

.github/workflows/test.yml
[codecov-action](https://github.com/codecov/codecov-action) v4 requires token.
ref: https://github.com/cybozu/duck/pull/993
=> ci: add token for codecov v4

examples/.eslintrc.json, examples/build-js/bootstrap.js, examples/build-soy/bootstrap.js
enable `goog.ENABLE_DEBUG_LOADER` in RAW mode for the latest closure-library.
=> docs: fix examples raw mode
